#!/usr/bin/env bash
#
# lifecycle:    onCreateCommand
# description:  This command is the first of three (along with updateContentCommand and postCreateCommand)
#               that finalizes container setup when a dev container is created. It and subsequent commands
#               execute inside the container immediately after it has started for the first time. Cloud
#               services can use this command when caching or prebuilding a container. This means that
#               it will not typically have access to user-scoped assets or secrets.
# author:       Peter Schmalfeldt <me@peterschmalfeldt.com>

# Create local Constants
CWD=$PWD

# Import Common Functions and Constants
source $CWD/.devcontainer/scripts/common

# Debug Container State
output 'Container Created'
