#!/usr/bin/env bash
#
# lifecycle:    postCreateCommand
# description:  This command is the last of three that finalizes container setup when a dev container is created.
#               It happens after updateContentCommand and once the dev container has been assigned to a user
#               for the first time. Cloud services can use this command to take advantage of user specific
#               secrets and permissions.
# author:       Peter Schmalfeldt <me@peterschmalfeldt.com>

# Create local Constants
CWD=$PWD
START=`date +%s`

# Import Common Functions and Constants
source $CWD/.devcontainer/scripts/common

# Run Base Installer
cd $CWD
output 'Installing Dependencies'
npm clean-install

# Install Complete
END=`date +%s`
RUNTIME=$((END-START))
HOURS=$((RUNTIME / 3600))
MINUTES=$(( (RUNTIME % 3600) / 60 ))
SECONDS=$(( (RUNTIME % 3600) % 60 ))

# Notify Developer
success "INSTALLATION COMPLETE: $(printf '%02d' $HOURS):$(printf '%02d' $MINUTES):$(printf '%02d' $SECONDS)"
notify 'Installation Complete' "Total Runtime: $(printf '%02d' $HOURS):$(printf '%02d' $MINUTES):$(printf '%02d' $SECONDS)"

# Start Dev Environment
output 'Running Dev Environment'
npm run dev
