#!/usr/bin/env bash
#
# lifecycle:    postCreateCommand
# description:  This command is the last of three that finalizes container setup when a dev container is created.
#               It happens after updateContentCommand and once the dev container has been assigned to a user
#               for the first time. Cloud services can use this command to take advantage of user specific
#               secrets and permissions.
# author:       Peter Schmalfeldt <me@peterschmalfeldt.com>

# Create local Constants
CWD=$PWD
START=`date +%s`

# Import Common Functions and Constants
source $CWD/.devcontainer/scripts/common

## Start Post Create Command
make_header 'Intiliaizing Dev Container'

# Switch to Project Directory
cd $CWD

# Start Installation
output 'Switch to Supported Node Version'
nvm use

output 'Installing Dependencies'
npm clean-install

# Run CLI Commands to Build Documentation ( need to complete each stage before moving to next )
output 'Initialize and Download Resources'
DEBUG=sfcc-docs:* $CWD/bin/cli.mjs init

output 'Cleanup HTML for Markdown'
for f in $CWD/.b2c-dev-doc/versions/*; do [ -d "$f" ] && DEBUG=sfcc-docs:* $CWD/bin/cli.mjs prep --version `basename "$f"`; done

output 'Update Anchor Tags in HTML'
for f in $CWD/.b2c-dev-doc/versions/*; do [ -d "$f" ] && DEBUG=sfcc-docs:* $CWD/bin/cli.mjs update-links --version `basename "$f"`; done

output 'Convert HTML to Markdown'
for f in $CWD/.b2c-dev-doc/versions/*; do [ -d "$f" ] && DEBUG=sfcc-docs:* $CWD/bin/cli.mjs convert --version `basename "$f"`; done

output 'Build Navigation for Version'
for f in $CWD/.b2c-dev-doc/versions/*; do [ -d "$f" ] && DEBUG=sfcc-docs:* $CWD/bin/cli.mjs build-nav --version `basename "$f"`; done

output 'Build Version DIFFs'
DEBUG=sfcc-docs:* $CWD/bin/cli.mjs diff

# Install Complete
END=`date +%s`
RUNTIME=$((END-START))
HOURS=$((RUNTIME / 3600))
MINUTES=$(( (RUNTIME % 3600) / 60 ))
SECONDS=$(( (RUNTIME % 3600) % 60 ))

# Notify Developer
success "INSTALLATION COMPLETE: $(printf '%02d' $HOURS):$(printf '%02d' $MINUTES):$(printf '%02d' $SECONDS)"
notify 'Installation Complete' "Total Runtime: $(printf '%02d' $HOURS):$(printf '%02d' $MINUTES):$(printf '%02d' $SECONDS)"

# Start Dev Environment
output 'Running Dev Environment'
npm run dev
