name: Bug Report
description: File a bug report
labels: ['Bug Report']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: issue-checklist
    attributes:
      label: 'Issue Checklist:'
      description: "I've verified the following before submitting this new issue:"
      options:
        - label: No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
          required: true
        - label: No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
          required: true
        - label: I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
          required: true
        - label: I'm following our [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what happened, and please attach any screenshots or log files.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which Browser were you using?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
        - Brave
        - Other
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Which Operating System were you using?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to produce this issue.
      description: Please be as specific as possible.
      placeholder: Please provide all the details we'll need to duplicate this issues ( URL you were on, what you clicked on, etc. )
    validations:
      required: true
