name: Requested Change
description: This is a Requested Change to the project
labels: [Requested Change]
body:
  - type: markdown
    attributes:
      value: |
        Please let us know what you think we should change.
  - type: checkboxes
    attributes:
      label: Checklist
      description: "I've verified the following:"
      options:
        - label: There are no matching [Open Requested Changes](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Requested+Change"+is%3Aopen)
          required: true
        - label: There are no matching [Closed Requested Changes](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Requested+Change"+is%3Aclosed)
          required: true
        - label: I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
          required: true
        - label: I'm following our [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    attributes:
      label: Describe the Problem
      description: Is your requested change related to a problem? Please describe.
      placeholder: A clear and concise description of what the request is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
