name: Continuous Integration
on:
  push:
    branches:
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=current_date::$(date +"%Y%m%dT%H%M%S")"
      - name: install packages
        run: npm ci
      - name: lint project
        run: npm run lint
      - name: test project
        run: 'npm run test:unit'
      - name: production build (sfra-webpack-builder)
        run: npm run prod
      - name: package cartridges recursively  (b2c-tools custom script)
        run: >-
          ./cli.js package --code-version "latest-${{
          steps.vars.outputs.sha_short}}-${{ steps.vars.outputs.current_date }}"
      - name: deploy and activate (sfcc-ci)
        run: >
          npm run sfcc-ci -- client:auth npm run sfcc-ci -- code:deploy
          "${CODE_VERSION}.zip" -i ${{secrets.SFCC_SERVER}} -a
        env:
          CODE_VERSION: >-
            latest-${{ steps.vars.outputs.current_date }}-${{
            steps.vars.outputs.sha_short }}
          SFCC_OAUTH_CLIENT_ID: '${{secrets.SFCC_OAUTH_CLIENT_ID}}'
          SFCC_OAUTH_CLIENT_SECRET: '${{secrets.SFCC_OAUTH_CLIENT_SECRET}}'
      - name: run migrations
        run: ./cli.js import migrate
        env:
          SFCC_SERVER: '${{secrets.SFCC_SERVER}}'
          SFCC_OAUTH_CLIENT_ID: '${{secrets.SFCC_OAUTH_CLIENT_ID}}'
          SFCC_OAUTH_CLIENT_SECRET: '${{secrets.SFCC_OAUTH_CLIENT_SECRET}}'
