name: Continuous Integration
on:
  push:
    branches:
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=current_date::$(date +"%Y%m%dT%H%M%S")"
      - name: install packages
        run: npm ci
