name: Lint and Test
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch: null
jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: npm run lint
